### ISSUE TITLE
Cannot compile on 4.23

### ISSUE THREAD

**Issue by xakod** [robertsmieja/UE4-Maze#1]
> Running D:/UnrealEngine/UE_4.23/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/Username/Documents/Unreal Projects/UE4-Maze/Maze/Maze.uproject" -game -rocket -progress -log="C:\Users\Username\Documents\Unreal Projects\UE4-Maze\Maze/Saved/Logs/UnrealVersionSelector-2019.11.28-20.21.57.log"
Discovering modules, targets and source code for project...
While compiling C:\Users\Username\Documents\Unreal Projects\UE4-Maze\Maze\Intermediate\Build\BuildRules\MazeModuleRules.dll:
c:\Users\Username\Documents\Unreal Projects\UE4-Maze\Maze\Source\Maze.Target.cs(19,12) : error CS0246: ?? 㤠???? ????? ??? ⨯? ??? ?????࠭?⢠ ???? "UEBuildBinaryConfiguration" (?ய?饭? ??४⨢? using ??? ??뫪? ?? ᡮ????)
c:\Users\Username\Documents\Unreal Projects\UE4-Maze\Maze\Source\MazeEditor.Target.cs(19,12) : error CS0246: ?? 㤠???? ????? ??? ⨯? ??? ?????࠭?⢠ ???? "UEBuildBinaryConfiguration" (?ய?饭? ??४⨢? using ??? ??뫪? ?? ᡮ????)
ERROR: Unable to compile source files.

Hello, try to compile it, but catch this

**Comment by robertsmieja** [comment]
I will take a look and try upgrading it to Unreal Engine 4.23.

The project was made with Unreal Engine 4.4 several years ago, and I have no idea what work needs to be done to make the code compatible.

**Comment by robertsmieja** [comment]
The code is compiling and launching under UE 4.23.1 as of this commit - https://github.com/robertsmieja/UE4-Maze/commit/9dec2b59fbf3a34b7ba11aeccfdc7bf03720a286

Please re-open this issue if you are still having issues.
